"""add_notes_title_and_updated_at

Revision ID: 4b8e17982eb0
Revises: 0001
Create Date: 2026-02-19 23:13:48.868017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b8e17982eb0'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('title', sa.String(), nullable=True))
    op.add_column('notes', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('notes', 'content',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('notes', 'updated_at')
    op.drop_column('notes', 'title')
    # ### end Alembic commands ###
